{% set name = "gepa" %}
{% set version = "0.0.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 83c52d1c640f68f049ffa533fc70d0d7216aa8ac99c418ba3441bdac7d037855

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - python-build
    - setuptools >=77.0.1
    - wheel
  run:
    - python
  run_constrained:
    # --- Python < 3.14 ---
    - litellm >=1.64.0       # [py<314]
    - datasets >=2.14.6      # [py<314]
    - mlflow >=3.0.0         # [py<314]
    - wandb                  # [py<314]
    # --- Python >= 3.14 ---
    - litellm >=1.81.0       # [py>=314]
    - datasets >=4.5.0      # [py>=314]
    - mlflow-skinny >=3.8.1  # [py>=314]
    - wandb >=0.23.0        # [py>=314]
    - pyarrow >=22.0.0      # [py>=314]
    - pydantic >=2.12.0     # [py>=314]
    - tiktoken >=0.12.0     # [py>=314]
    # --- Common ---
    - tqdm >=4.66.1

# fixture 'rng' not found
{% set deselect_tests = "--deselect=tests/test_state.py::test_dynamic_validation" %}
# FileNotFoundError: [Errno 2] No such file or directory: '$SRC_DIR/tests/legacy_test_state.bin'
{% set deselect_tests = deselect_tests + " --deselect=tests/test_state.py::test_load_legacy_state" %}
# fixture 'mocked_lms' not found
{% set deselect_tests = deselect_tests + " --deselect=tests/test_state.py::test_e2e_resume_run" %}

test:
  source_files:
    - tests
  imports:
    - gepa
    - gepa.adapters
    - gepa.core
    - gepa.gepa_utils
    - gepa.logging
    - gepa.proposer
    - gepa.strategies
    - gepa.utils
  requires:
    - pip
    - pytest
    - cloudpickle
  commands:
    - pip check
    - pytest -v tests {{ deselect_tests }}

about:
  home: https://github.com/gepa-ai/gepa
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for optimizing textual system components (AI prompts, code snippets, etc.) using LLM-based reflection and Pareto-efficient evolutionary search
  description: |
    A framework for optimizing textual system components 
    (AI prompts, code snippets, etc.) using LLM-based reflection 
    and Pareto-efficient evolutionary search
  doc_url: https://github.com/gepa-ai/gepa
  dev_url: https://github.com/gepa-ai/gepa

extra:
  recipe-maintainers:
    - moritzwilksch
